### ISSUE TITLE
Error in RTDETR checkpoint download

### ISSUE THREAD

**Issue by patel-zeel** [roboflow/model-leaderboard#18]
Hi @LinasKo and @onuralpszr,

Thanks a lot for developing this comprehensive leaderboard!

I was trying to run `rtdetr_r101vd` model, but it seems there is some issue with downloading the checkpoint. It could also be a temporary issue but I thought to check with you.

The code I run is the following:
```
cd models/object_detection/rtdetr_r101vd
python run.py
```

Error trace:
```py
UserWarning: Can't initialize NVML
UserWarning: You are about to download and run code from an untrusted repository. In a future release, this won't be allowed. To add the repository to your trusted list, change the command to {calling_fn}(..., trust_repo=False) and a command prompt will appear asking for an explicit confirmation of trust, or load(..., trust_repo=True), which will assume that the prompt is to be answered with 'yes'. You can also use load(..., trust_repo='check') which will only prompt for confirmation if the repo is not already trusted. This will eventually be the default behaviour
Downloading: "https://github.com/lyuwenyu/RT-DETR/zipball/main" to /home/patel_zeel/.cache/torch/hub/main.zip
Downloading: "https://github.com/lyuwenyu/storage/releases/download/v0.1/rtdetr_r101vd_6x_coco_from_paddle.pth" to /home/patel_zeel/.cache/torch/hub/checkpoints/rtdetr_r101vd_6x_coco_from_paddle.pth
Traceback (most recent call last):
  File "/opt/anaconda3/envs/zeel_py310/lib/python3.10/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/opt/anaconda3/envs/zeel_py310/lib/python3.10/http/client.py", line 1283, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/opt/anaconda3/envs/zeel_py310/lib/python3.10/http/client.py", line 1329, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/opt/anaconda3/envs/zeel_py310/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/opt/anaconda3/envs/zeel_py310/lib/python3.10/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/opt/anaconda3/envs/zeel_py310/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/opt/anaconda3/envs/zeel_py310/lib/python3.10/http/client.py", line 1455, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/opt/anaconda3/envs/zeel_py310/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/opt/anaconda3/envs/zeel_py310/lib/python3.10/ssl.py", line 1071, in _create
    self.do_handshake()
  File "/opt/anaconda3/envs/zeel_py310/lib/python3.10/ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/patel_zeel/model-leaderboard/models/object_detection/rtdetr_r101vd/run.py", line 70, in <module>
    model = torch.hub.load(HUB_URL, MODEL_NAME, pretrained=True)
  File "/opt/anaconda3/envs/zeel_py310/lib/python3.10/site-packages/torch/hub.py", line 568, in load
    model = _load_local(repo_or_dir, model, *args, **kwargs)
  File "/opt/anaconda3/envs/zeel_py310/lib/python3.10/site-packages/torch/hub.py", line 597, in _load_local
    model = entry(*args, **kwargs)
  File "/home/patel_zeel/.cache/torch/hub/lyuwenyu_RT-DETR_main/hubconf.py", line 135, in rtdetr_r101vd
    return _build_model(args, )
  File "/home/patel_zeel/.cache/torch/hub/lyuwenyu_RT-DETR_main/hubconf.py", line 36, in _build_model
    checkpoint = _load_checkpoint(args.resume, map_location='cpu') 
  File "/home/patel_zeel/.cache/torch/hub/lyuwenyu_RT-DETR_main/hubconf.py", line 26, in _load_checkpoint
    state = torch.hub.load_state_dict_from_url(path, map_location=map_location)
  File "/opt/anaconda3/envs/zeel_py310/lib/python3.10/site-packages/torch/hub.py", line 760, in load_state_dict_from_url
    download_url_to_file(url, cached_file, hash_prefix, progress=progress)
  File "/opt/anaconda3/envs/zeel_py310/lib/python3.10/site-packages/torch/hub.py", line 622, in download_url_to_file
    u = urlopen(req)
  File "/opt/anaconda3/envs/zeel_py310/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/anaconda3/envs/zeel_py310/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/opt/anaconda3/envs/zeel_py310/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/opt/anaconda3/envs/zeel_py310/lib/python3.10/urllib/request.py", line 557, in error
    result = self._call_chain(*args)
  File "/opt/anaconda3/envs/zeel_py310/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/opt/anaconda3/envs/zeel_py310/lib/python3.10/urllib/request.py", line 749, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/opt/anaconda3/envs/zeel_py310/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/opt/anaconda3/envs/zeel_py310/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/opt/anaconda3/envs/zeel_py310/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/opt/anaconda3/envs/zeel_py310/lib/python3.10/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/opt/anaconda3/envs/zeel_py310/lib/python3.10/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 104] Connection reset by peer>
```

**Comment by onuralpszr** [comment]
@patel-zeel  all fine,  no trouble at all. You're welcome 👍
